version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=development
    restart: unless-stopped